#
# Makefile for RZ/N1 (R9A06G032) Architecture files.
#

ccflags-$(CONFIG_ARCH_MULTIPLATFORM) := -I$(srctree)/arch/arm/mach-rzn1/include

obj-$(CONFIG_ARCH_RZN1)		+= sysctrl-rzn1.o
obj-$(CONFIG_RZN1_A5PSW_WORKAROUND)	+= rzn1-a5psw-workaround.o
